name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_SECRET_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: |
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_PUBLIC_IP}} "
          cd aws-cicd

          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR=\"$HOME/.nvm\"
          [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"
          nvm install 16
          nvm use 16

          node -v

          git pull origin main || exit 1
          npm install || exit 1
          npm run build || exit 1

          sudo -s || exit 1
          pkill node || exit 1
          npm run start & npx wait-on http://localhost || exit 1
          exit
          "
