name: test and deploy

on:
  push:
    branches:
      - main

permissions: 
  id-token: write # JWT를 요청하는데 필요
  contents: read  # actions/checkout에 필요

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test with Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::721509753078:role/GithubOIDC # arn
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}