name: test and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm packages
        run: npm ci

      - name: Install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server --daemonize yes --requirepass test_env --port 6380

      - name: Run test
        run: npm run test:ci

      - name: Run build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test # 의존성
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up SSH
        run: |
          node -v
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_SECRET_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: |
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USERNAME}}@${{secrets.SSH_PUBLIC_IP}} "

            sudo -s
            cd aws-cicd

            git pull || exit 1
            npm install || exit 1
            npm run build || exit 1
            pm2 reload
            exit
          "
